### ISSUE TITLE
nginx default ingress

### ISSUE THREAD

**Issue by adonm** [adonm/iac_templates#1]
Setup some default ingress/annotations to use sslip.io if not specified:

```yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/managed-by: aks-app-routing-operator
    app.kubernetes.io/name: nginx
  name: webapprouting.kubernetes.azure.com
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: webapprouting.kubernetes.azure.com/nginx
```
